add fetch logic
kolike/todo-list-app pull request #12
Opened 2023-09-21 12:53 UTC by kolike

2023-09-21 16:33 UTC, 0xDmitry requested changes

2023-09-21 16:33 UTC, 0xDmitry commented on components/TodoList.js
> +import { useEffect } from 'react';
?

2023-09-21 16:33 UTC, 0xDmitry commented on app/page.js
> +  const url = 'http://localhost:3000/api/todos/';
Просто `/api/todos`, и давай без глобальной переменной, лучше для каждого запроса пропишем то что надо

2023-09-21 16:33 UTC, 0xDmitry commented on app/page.js
> +import { useState, useEffect, useCallback } from 'react';
`useCallback` лишний

2023-09-21 16:33 UTC, 0xDmitry commented on app/page.js
> +  const getData = async () => {
давай до юз эффекта объявим

2023-09-21 16:33 UTC, 0xDmitry commented on app/page.js
> +    try {
Зачем тут `try/catch`? Без него и так ошибка вылетит, причем более подробная

2023-09-21 16:33 UTC, 0xDmitry commented on app/page.js
> +      setData(json);
👍

2023-09-21 16:33 UTC, 0xDmitry commented on app/page.js
> +      console.log('Successful file upload:', json);
Надо не логировать, а сетить стейт, и так для всех запросов

2023-09-21 16:33 UTC, 0xDmitry commented on app/page.js
>      setData((data) => data.filter((item) => item.id !== id));
Работа с этим стейтом должна сводиться только к передаче данных с сервера

2023-09-22 06:58 UTC, kolike commented on app/page.js
> +      setData(json);
?

2023-09-22 11:41 UTC, 0xDmitry commented on app/page.js
> +    removeTodo(id);
Зачем оборачивать функцию `removeTodo` в функцию `deleteTodo`?

2023-09-22 11:41 UTC, 0xDmitry commented on app/page.js
> +    postTodo(newTodo);
Такой же вопрос

2023-09-22 11:41 UTC, 0xDmitry commented on app/page.js
> +    data.map((item) => {
Тут нужен `map` ?

2023-09-22 11:41 UTC, 0xDmitry commented on app/page.js
> +    const json = await response.json();
давай переименуем в `data`

2023-09-22 11:41 UTC, 0xDmitry commented on app/page.js
> +  const postTodo = async (data) => {
`data` -> `newTodo`

2023-09-22 11:49 UTC, kolike commented on app/page.js
> +    data.map((item) => {
добавил forEach

2023-09-22 16:27 UTC, 0xDmitry approved these changes

2023-09-22 16:27 UTC, merged