add more styles
kolike/todo-list-app pull request #5
Opened 2023-09-15 19:54 UTC by kolike

2023-09-16 10:49 UTC, 0xDmitry requested changes

2023-09-16 10:49 UTC, 0xDmitry commented on app/page.js
> +        {data[0] === undefined ? <h3>Todo list is empty</h3> : null}
А если по 0 индексу ниче нет, а по следующему есть?) На пустой массив когда хотят проверить смотрят чему равен `length` обычно

2023-09-16 10:49 UTC, 0xDmitry commented on components/AddTodoListItem.js
> +  &:hover {
Чет выглядит не оч)

![image](https://github.com/kolike/todo-list-app/assets/61683409/b6c0b286-8524-4217-b2cc-8bee3dad4739)

Попробуй темную тень мб

2023-09-16 10:49 UTC, 0xDmitry commented on components/AddTodoListItem.js
> +        <label for="isImportant">Important todo?</label>
Тут давай тоже `Todo` с большой буквы

2023-09-16 10:49 UTC, 0xDmitry commented on components/TodoListItem.css
> +.isDone {
Не брат, через css мы делать не будем)

2023-09-16 10:49 UTC, 0xDmitry commented on components/TodoListItem.js
> +  &:hover {
А че тут с форматированием? 🤔

2023-09-16 10:49 UTC, 0xDmitry commented on components/TodoListItem.js
> +import classNames from 'classnames';
Эту либу можно удалить, мы через `styled components` это сделаем

2023-09-16 10:49 UTC, 0xDmitry commented on components/TodoListItem.js
> +      <Row className={isDoneClassName}>
https://styled-components.com/docs/basics#adapting-based-on-props

Надо сделать через `styled components`, см пример

2023-09-16 10:52 UTC, 0xDmitry commented on components/TodoListItem.js
> +    text-shadow: 1px 1px 1px #000;
Тень у текста мне чет тоже не заходит

2023-09-17 11:34 UTC, kolike commented on app/page.js
> +        {data[0] === undefined ? <h3>Todo list is empty</h3> : null}
согласен

2023-09-17 11:36 UTC, kolike commented on components/AddTodoListItem.js
> +  &:hover {
применил темную тень

2023-09-17 17:33 UTC, merged